config/routes.rb
Rails.application.routes.draw do
  root :to => 'lessons#index'

  resources :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  validates :title, :body, :presence => true

  def next
    Lesson.find_by number: number + 1
  end

  def prev
    Lesson.find_by number: number - 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.number = Lesson.count + 1
    if @lesson.save
      flash[:notice] = "Lesson successfully added!"
      redirect_to lessons_path(@lesson)
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to lessons_path
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    flash[:notice] = "Lesson destruction successfully deployed."
    redirect_to lessons_path
  end

  private
    def lesson_params
      params.require(:lesson).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if @lesson.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @lesson.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnHowToRails</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat|Roboto+Slab:400,300' rel='stylesheet' type='text/css'>  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class='container'>
  <%= yield %>
</div>
</body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= bootstrap_form_for(@lesson) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body, rows: 15 %>
  <%= f.submit class: 'btn btn-info' %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit <%= @lesson.title %></h1>


<%= render 'form' %>

<%= link_to "back", lessons_path %>

app/views/lessons/index.html.erb
<h1>Lessons</h1>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= link_to lesson.title, lesson_path(lesson) %></li>
  <% end %>
</ul>

<%= link_to "Create new lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<h1><%= @lesson.title %></h1>

<h4><%= @lesson.body %></h4>

<h5><%= @lesson.number %></h5>

<p><%= link_to "Edit", edit_lesson_path(@lesson) %></p>

<p><%= link_to "Delete", lesson_path(@lesson),
                          :data => {:confirm => "Are you absolutely sure? This will destroy your lesson!",
                          :method => "delete"}%></p>


<p><% if @lesson.prev %></p>
  <%= link_to "<= Previous", lesson_path(@lesson.prev) %>
<% end %>
<p><% if @lesson.next %></p>
  <%= link_to "Next =>", lesson_path(@lesson.next) %>
<% end %>
<br />
<br />
<%= link_to "View all lessons", lessons_path %>

app/views/shared/_header.html.erb
<h1><%= link_to 'Learn how to Rails', lesson_path %> <%=" | #{title}"%></h1>

<%= flash[:alert] %>
<%= flash[:notice] %>